import './globals.css'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
// import { getServerSession } from 'next-auth/next'
// import { SessionProvider } from 'next-auth/react'
import { Session } from 'next-auth'
import { headers } from 'next/headers'
import AuthContext from './AuthContext'
// import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function getSession(cookie: string): Promise<Session> {
  const response = await fetch(`${process.env.LOCAL_AUTH_URL}/api/auth/session`, {
    headers: {
      cookie,
    },
  });

  const session = await response.json();

  return Object.keys(session).length > 0 ? session : null;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // console.log('authOptions: -->', authOptions);
  // const session = await getServerSession(authOptions);
  const session = await getSession(headers().get('cookie') ?? '');
  console.log('session:--->', session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col'>
          <div className='mb-20'></div>
          <div className='mb-18 mt-20'>
            <AuthContext session={session}>
              {children}
            </AuthContext>
          </div>
          <div className='fixed bottom-10 mt-12 pt-20ml-24 pl-96'></div>
        </div>
      </body>
    </html>
  )
}
