import './globals.css'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
// import { Session } from 'next-auth'
// import { headers } from 'next/headers'
// import AuthContext from '../components/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// async function getSession(cookie: string): Promise<Session> {
//   const response = await fetch(`${process.env.LOCAL_AUTH_URL}/api/auth/session`, {
//     headers: {
//       cookie,
//     },
//   });

//   const session = await response.json();

//   return Object.keys(session).length > 0 ? session : null;
// }

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const session = await getSession(headers().get('cookie') ?? '');
  // console.log('session:--->', session);

  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex flex-col h-full">
            <div className="flex-grow">
            {/* <AuthContext session={session}> */}
              {children}
            {/* </AuthContext> */}
          </div>
          <div className='fixed bottom-10 mt-12 pt-20ml-24 pl-96'></div>
        </div>
      </body>
    </html>
  )
}
